'use client';

import { ShieldAlert } from 'lucide-react';

const MOCK_EVENTS = [
  { id: 's1', severity: 'HIGH', message: 'Brute force attempt detected from 103.xx.xx.xx', time: '12 min ago', action: 'IP blocked automatically' },
  { id: 's2', severity: 'MEDIUM', message: 'Unusual login location for admin user', time: '2 hrs ago', action: 'Email notification sent' },
  { id: 's3', severity: 'LOW', message: 'New API key generated by partner FitLife', time: '5 hrs ago', action: 'Logged' },
  { id: 's4', severity: 'HIGH', message: 'Mass token refund request (>100 tokens)', time: '1 day ago', action: 'Pending review' },
];

const SEVERITY_COLOR: Record<string, string> = {
  HIGH: '#dc2626', MEDIUM: '#d97706', LOW: '#16a34a',
};

export default function SecurityPage() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
      <h1 style={{ margin: 0, fontSize: 'var(--font-size-2xl)' }}>Security</h1>
      <div className="dashboard-card">
        <h3 style={{ margin: '0 0 var(--space-4) 0', fontSize: 'var(--font-size-md)' }}>
          <ShieldAlert size={18} style={{ display: 'inline', marginRight: 8, verticalAlign: 'text-bottom' }} />
          Security Events
        </h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
          {MOCK_EVENTS.map((e) => (
            <div key={e.id} style={{
              padding: 'var(--space-3) var(--space-4)', borderRadius: 'var(--radius-md)',
              background: 'var(--bg-app)',
              borderLeft: `3px solid ${SEVERITY_COLOR[e.severity]}`,
              display: 'flex', alignItems: 'center', gap: 'var(--space-4)',
            }}>
              <span style={{
                fontSize: 10, fontWeight: 700, color: SEVERITY_COLOR[e.severity],
                background: `${SEVERITY_COLOR[e.severity]}15`,
                padding: '2px 6px', borderRadius: 4, textTransform: 'uppercase',
              }}>
                {e.severity}
              </span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 'var(--font-weight-medium)', color: 'var(--text-heading)' }}>{e.message}</div>
                <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-tertiary)' }}>Action: {e.action}</div>
              </div>
              <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-tertiary)', whiteSpace: 'nowrap' }}>{e.time}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
